# thanks getchoo :3

name: build and cache stuff
# this is for uploading images to a container registry when
# changes are made to `main`

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      REGISTRY: ghcr.io
      USERNAME: uku3lig

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      
      - name: setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: uku3lig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      - name: build derivation
        run: nix build --accept-flake-config -L .#api-rs

      - name: fetch docker image
        run: |
          nix build --accept-flake-config -L .#container
          readlink result | xargs -I {} cp {} api-rs.tar.gz

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ github.token }}

      - name: upload to registry
        env:
          PUSH_PREFIX: ${{ env.REGISTRY }}/${{ env.USERNAME }}
        run: |
          docker load < api-rs.tar.gz
          docker tag api-rs:latest ${{ env.PUSH_PREFIX }}/api-rs:latest
          docker push ${{ env.PUSH_PREFIX }}/api-rs:latest
