name: build and cache stuff

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19

      - name: setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: uku3lig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: build derivation
        run: nix build --accept-flake-config -L
